[package]
name = "styx-cst"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Lossless Concrete Syntax Tree for the Styx configuration language"
repository.workspace = true

[dependencies]
styx-parse.workspace = true
rowan = "0.16"

[dev-dependencies]
