specs:
  - name: parser
    prefix: r
    include:
      - docs/020-parser-spec.md
    impls:
      - name: rust
        include:
          - "**/*.rs"

  - name: schema
    prefix: r
    include:
      - docs/030-schema-spec.md
    impls:
      - name: rust
        include:
          - "**/*.rs"

  - name: diagnostics
    prefix: r
    include:
      - docs/050-diagnostics-spec.md
    impls:
      - name: rust
        include:
          - "**/*.rs"
