id = "styx"
name = "Styx"
description = "Styx configuration language support with syntax highlighting and LSP"
version = "0.1.0"
schema_version = 1
authors = ["Amos Wenger <amos@bearcove.eu>"]
repository = "https://github.com/bearcove/styx"

[grammars.styx]
repository = "https://github.com/bearcove/styx"
path = "crates/tree-sitter-styx"
rev = "081b5fde1e65b3184acfaa47ebd411ed47b25853"

[language_servers.styx-lsp]
name = "Styx LSP"
languages = ["Styx"]
