id = "styx"
name = "Styx"
description = "Styx configuration language support with syntax highlighting and LSP"
version = "0.1.0"
schema_version = 1
authors = ["Amos Wenger <amos@bearcove.eu>"]
repository = "https://github.com/bearcove/styx"

[grammars.styx]
repository = "https://github.com/bearcove/styx"
path = "crates/tree-sitter-styx"
rev = "f1fdd2a795e0404fda24b6f9a7eaf70e8918d147"

[language_servers.styx-lsp]
name = "Styx LSP"
languages = ["Styx"]
