[package]
name = "styx-compat-tests"
version = "0.1.0"
edition.workspace = true
description = "Cross-compatibility tests between facet-styx and serde_styx"
publish = false

[dependencies]

[dev-dependencies]
facet.workspace = true
facet-styx.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_styx = { path = "../serde_styx" }
